_wandb:
    value:
        cli_version: 0.17.5
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 5
                - 53
                - 55
                - 105
            "2":
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.10
            "5": 0.17.5
            "8":
                - 5
            "12": 0.17.5
            "13": linux-x86_64
model_name:
    value: Gradient Boosting
regressor__max_depth:
    value: 9
regressor__min_samples_leaf:
    value: 10
regressor__n_estimators:
    value: 100
